"""Test1

Revision ID: 862c98ace7dc
Revises: aa6ea29b7e09
Create Date: 2025-02-03 18:41:36.150695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862c98ace7dc'
down_revision = 'aa6ea29b7e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))
        batch_op.alter_column('team',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('team',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
